# **HW #0 Exploratory Data Analysis (EDA) with Pandas**

### **TODO: Martin Colmenero**

**Important Note:** *During the Wednesday's class, we will engage in a set of exercises using Pandas and the `flights.csv` dataset, which will equip you with the essential knowledge about how to use Pandas that you might need to fulfill this assignment.*

* In this homework, we will explore the `flights.csv` dataset that contains information about flight records from 2013. Using your (recently) acquired data analysis skills, the Pandas library, and the `flights.csv` dataset, implement the following questions in Python.

In [1]:
# import the libraries
import pandas as pd
import numpy as np

In [2]:
# This is specifically for Google Colab, you need to mount the Google drive first

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('flights.csv', index_col=False)

### **Question One:** (2 points) Select all rows where the carrier is 'UA' and the difference between departure time and scheduled departure time is more than 2 minutes.

In [15]:
#TODO: Your code goes here
ua_departure_difference = df[(df['carrier'] == 'UA') & (abs(df['dep_time'] - df['sched_dep_time']) <= 2.0)]
ua_departure_difference

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,1/1/2013 5:00
24,24,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,1077,N53442,EWR,MIA,157.0,1085,6,7,1/1/2013 6:00
37,37,2013,1,1,628.0,630,-2.0,1016.0,947,29.0,UA,1665,N33289,EWR,LAX,366.0,2454,6,30,1/1/2013 6:00
49,49,2013,1,1,646.0,645,1.0,910.0,916,-6.0,UA,883,N569UA,LGA,DEN,243.0,1620,6,45,1/1/2013 6:00
50,50,2013,1,1,646.0,645,1.0,1023.0,1030,-7.0,UA,1496,N38727,EWR,SNA,380.0,2434,6,45,1/1/2013 6:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,960,2013,1,2,732.0,732,0.0,1047.0,1040,7.0,UA,1509,N73291,LGA,IAH,230.0,1416,7,32,2/1/2013 7:00
964,964,2013,1,2,734.0,732,2.0,844.0,853,-9.0,UA,1199,N37408,EWR,BOS,34.0,200,7,32,2/1/2013 7:00
971,971,2013,1,2,741.0,740,1.0,1005.0,1019,-14.0,UA,328,N533UA,LGA,DEN,220.0,1620,7,40,2/1/2013 7:00
975,975,2013,1,2,745.0,746,-1.0,1118.0,1129,-11.0,UA,1668,N37287,EWR,SFO,350.0,2565,7,46,2/1/2013 7:00
994,994,2013,1,2,804.0,805,-1.0,1039.0,1110,-31.0,UA,423,N528UA,EWR,PDX,310.0,2434,8,5,2/1/2013 8:00


### **Question Two:** (2 points) How many unique airlines are there in the dataset?

In [47]:
#TODO: Your code goes here
unique_airlines = df.groupby('carrier').size()
unique_airlines.size

## (14)
## There are 14 unique airlines

14

### **Question Three:** (3 points) Which carrier has the longest cumulative departure delay?

In [67]:
#TODO: Your code goes here
# Group by carrier and sum the departure delays, then sort in descending order
# Get the carrier with the longest delays in sum
carrier_delay_list = df.groupby('carrier')['dep_delay'].sum()
carrier_delay_list.sort_values(ascending = False) # Displays list in descending order

carrier_with_longest_delay = carrier_delay_list['EV'] # 'EV' had the longest departure delays
print(carrier_with_longest_delay)

3947.0

 ### **Question Four:** (3 points) Which carrier has the single longest departure delay?

In [77]:
#TODO: Your code goes here
carrier_delay_list = df.groupby('carrier')['dep_delay'].max()
carrier_delay_list.sort_values(ascending = False)

# single_longest_dep_delay = carrier_delay_list['MQ']
# single_longest_dep_delay
# 'MQ' had the the single longest departure delay: 853.0

carrier
MQ    853.0
EV    379.0
AA    285.0
9E    255.0
B6    156.0
UA    144.0
DL    105.0
WN     34.0
US     15.0
FL      9.0
VX      3.0
AS     -1.0
F9     -2.0
HA     -3.0
Name: dep_delay, dtype: float64

# **TODO: When done, please submit your `ipynb` file on Canvas.**